version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"      # Internal 5672 exposed as 5673
      - "15673:15672"    # RabbitMQ UI

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
